// const selectAll = document.querySelectorAll(".progress")
// selectAll[0].addEventListener("click", function(){
//         selectAll[0].classList.add("active")
//     selectAll[1].classList.remove("active")
//     selectAll[2].classList.remove("active")
//     selectAll[3].classList.remove("active")
//     selectAll[4].classList.remove("active")
// })
// selectAll[1].addEventListener("click", function(){
//     selectAll[0].classList.add("active")
// selectAll[1].classList.add("active")
// selectAll[2].classList.remove("active")
// selectAll[3].classList.remove("active")
// selectAll[4].classList.remove("active")
// })
// selectAll[2].addEventListener("click", function(){
//     selectAll[0].classList.add("active")
// selectAll[1].classList.add("active")
// selectAll[2].classList.add("active")
// selectAll[3].classList.remove("active")
// selectAll[4].classList.remove("active")
// })
// selectAll[3].addEventListener("click", function(){
//     selectAll[0].classList.add("active")
// selectAll[1].classList.add("active")
// selectAll[2].classList.add("active")
// selectAll[3].classList.add("active")
// selectAll[4].classList.remove("active")
// })
// selectAll[4].addEventListener("click", function(){
//     selectAll[0].classList.add("active")
// selectAll[1].classList.add("active")
// selectAll[2].classList.add("active")
// selectAll[3].classList.add("active")
// selectAll[4].classList.add("active")
// })
